### ISSUE TITLE
can't open in terminal 

### ISSUE THREAD

**Issue by Pranjalmet** [abba23/spotify-adblock#29] opened 2021-07-18 18:24 UTC
when i try to run it in terminal using 

> LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify

Getting error
```
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
/opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
ERROR: ld.so: object '/usr/local/lib/spotify-adblock.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)

```

**Comment by abba23** [comment] 2021-07-18 18:29
Does `/usr/local/lib/spotify-adblock.so` exist? Did you perhaps forget to run `sudo make install`?

**Comment by Pranjalmet** [comment] 2021-07-18 18:32
yes  `/usr/local/lib/spotify-adblock.so` exist and i installed it using AUR so didn't have to `sudo make install` it, if I'm right

**Comment by abba23** [comment] 2021-07-18 18:33
Duplicate of #3

**Closed by abba23** 2021-07-18 18:33 UTC
