### ISSUE TITLE
Spotify-adblock not working on fedora and rhel-based distro.

### ISSUE THREAD

**Issue by tr1p0p** [abba23/spotify-adblock#26] opened 2021-07-15 14:17 UTC
The way rpm fusion install spotify (here : https://docs.fedoraproject.org/en-US/quick-docs/installing-spotify/) don't make possible the fact to launch spotify with the adblock.

Here a issue, show as close, when the issue is the same : https://github.com/abba23/spotify-adblock/issues/2 

The fact is : it's not working. Puting the line at the end of wrapper in usr/bin/spotify don't block audio/banner ads at all.

Flatpack not working either because it seem the script are made for ubuntu/debian, and for some reason spotify-adblock don't seem to see glibc on fedora 34 (even when it's the good version).

So i just say this project should add a line for rhel/fedora user for warning about this. Or maybe just found a way to make it work ? 
For the moment just one user say it launch, and we not having a single clue of how it do this (add a line ? Yeah but what spotify-adblock it use, this or the old archived version ? why one user say it work, the other, doing exactly the same, not working ?)

Thks a lot for the hard work.

**Comment by abba23** [comment] 2021-07-15 14:56
Duplicate of #2

**Closed by abba23** 2021-07-15 14:56 UTC
