### ISSUE TITLE
GLIBC_2.33 not found

### ISSUE THREAD

**Issue by d35r0n** [abba23/spotify-adblock#28] opened 2021-07-16 18:49 UTC
I was trying to use this adblock on Flatpak since I am using Manjaro. All the steps were smooth but the final running script doesn't work.

I used this:

```bash
flatpak run --command=sh com.spotify.Client -c 'eval "$(sed s#LD_PRELOAD=#LD_PRELOAD=$HOME/.spotify-adblock/spotify-adblock.so:#g /app/bin/spotify)"'
```

and I got the output as:

```
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/bin/spotify: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/user/.spotify-adblock/spotify-adblock.so)
```

I tried looking up for both of these errors but wasn't able to find a working solution

**Comment by abba23** [comment] 2021-07-16 18:57
Duplicate of #24

**Closed by abba23** 2021-07-16 18:57 UTC

**Comment by d35r0n** [comment] 2021-07-16 19:28
Oh, I never thought of using the AUR packages. I'm somewhat new to Linux. But thanks for the help! Also, I apologise for wasting your time with my stupidity.
